version: "3.8"

services:

  node-app:
    build: .
    container_name: node-app
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - SERVICE_NAME=node-test-service
      - OTEL_COLLECTOR_ENDPOINT=http://otel-collector:4318/v1/logs
    depends_on:
      - otel-collector

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    volumes:
      - ./otel-config.yaml:/etc/otelcol/config.yaml
    command: ["--config=/etc/otelcol/config.yaml"]
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - loki